-- PARA VALIDAR RUT PARA ENVÍO DE SMS O EMAIL ENTEL
-- ESTA QUERY MUESTRA LOS RUT A LOS QUE "SÍ" SE LES PUEDE MANDAR SMS O EMAIL.
-- HAY QUE FIJARSE EN EL DÍA DE AYER Y ANTES DE AYER EN LA QUERY.

SELECT DISTINCT 
    CONVERT(VARCHAR, RUT) AS RUT
FROM 
    B2C_OPER.DBO.[1009_RTG_0020ACSA_] WITH (NOLOCK)
WHERE 
    ISNULL(ULTIMA_GESTION, '') NOT IN ('BLOQUEO ACSA', 'BLOQUEO PAGO') -- BLOQUEOS RUT
    AND ISNULL(NOMBRE, '') <> 'SIN NOMBRE' -- Validar que el nombre no sea "SIN NOMBRE"

