-- PARA VALIDAR RUT PARA ENVÍO DE SMS O EMAIL ENTEL
-- ESTO MOSTRARÁ LOS RUT A LOS QUE "SÍ" SE LES PUEDE ENVIAR MASIVIDAD.
-- TENER EN CUENTA QUE LA TABLA [1009_RTG_0200ENTE_202502] Y [XXXX_SALDOS_0200ENTE] 
-- ESTÉN ACTUALIZADAS CON LA ÚLTIMA INFORMACIÓN DEL DÍA.
-- ESTA TABLA [XXXX_CUENTAS_0200ENTE] TIENE QUE CONTENER TODOS LOS RUT, CUENTAS, 
-- FOLIOS DE LO ASIGNADO EN EL MES. SE VA LLENANDO CUANDO EL CLIENTE ENVÍA ASIGNACIONES.

SELECT DISTINCT 
    CONVERT(VARCHAR, RUT) AS RUT
FROM 
    B2C_OPER.DBO.[1009_RTG_0200ENTE_] WITH (NOLOCK)
WHERE 
    ISNULL(NOMBRE, '') <> 'SIN NOMBRE' -- Validar que el nombre no sea "SIN NOMBRE"
    AND ISNULL(ULTIMA_GESTION, '') NOT LIKE '%BLOQUEO%'
    AND RUT IN (
        SELECT 
            A1.RUT
        FROM 
            B2C_OPER.DBO.[XXXX_CUENTAS_0200ENTE] A1 WITH (NOLOCK)
        INNER JOIN 
            B2C_OPER.DBO.[XXXX_SALDOS_0200ENTE] A2 WITH (NOLOCK)
        ON 
            A1.FOLIO = A2.[FOLIO DOC]
        GROUP BY 
            A1.RUT
    ) -- ESTO VALIDA LA VIGENCIA DEL RUT
