

SET DATEFIRST 1;
DECLARE @AYER				VARCHAR(8)=CONVERT(VARCHAR,DATEADD(DAY, IIF(DATEPART(WEEKDAY, GETDATE())>1,DATEPART(WEEKDAY, GETDATE())-1,NULL) - DATEPART(WEEKDAY, GETDATE()), CAST(GETDATE() AS DATE)),112)
DECLARE @ANTESDEAYER	VARCHAR(8)=CONVERT(VARCHAR,DATEADD(DAY, IIF(DATEPART(WEEKDAY, GETDATE())>2,DATEPART(WEEKDAY, GETDATE())-2,NULL) - DATEPART(WEEKDAY, GETDATE()), CAST(GETDATE() AS DATE)),112)
--PRINT @AYER
--PRINT @ANTESDEAYER

--A ESTOS RUT, "NO" SE LES PUEDE ENVIAR EMAIL. SI NO DA RESULTADO QUIERE DECIR QUE ESA SEMANA AUN NO LE ENVIAN EMAILS
SELECT RUT FROM(
SELECT RUT,Q=COUNT(*),FECHA_ENVIO=MAX(CONVERT(DATE,FECHA))
FROM B2C.DBO.[0900TRAF_202504MASI]WITH(NOLOCK)
WHERE CLIENTE ='0370FORU' AND TIPO='MAIL'	AND GESTION IN('Abierto','Sin apertura','ENTREGADO')
GROUP BY RUT)X WHERE X.Q>1 OR FECHA_ENVIO IN(@ANTESDEAYER,@AYER)